version: '3'
services:
  app:
    build: .
    depends_on:
      - morehomesdb
    links:
      - morehomesdb
    ports:
      - '3004:3004'
    expose:
      - '3004'
  morehomesdb:
    container_name: morehomes
    image: mysql:5.7
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'student'